apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      nodeSelector:
        cloud.google.com/gke-nodepool: {{ .Values.deployment.nodePool }}

      imagePullSecrets:
      - name: gcr-json-key
      containers:
      - name: {{ .Values.name }}
        image: {{ .Values.image.name }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: PORT
          value: "8080"

        - name: LOG_LEVEL
          value: "{{ .Values.logLevel }}"

        - name: DB_CONNECTION_STRING
          value: "{{ .Values.database.login }}:{{ .Values.database.pwd }}@({{ .Values.database.host }})/{{ .Values.database.name }}?parseTime=true"

        resources:
{{ toYaml .Values.resources | indent 10 }}

        livenessProbe:
          httpGet:
            path: "/health"
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 5
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 2